a3mg\RussianPostBundle\Model\AuthorisationFaultReason:
    xml_root_name: AuthorisationFaultReason
    xml_root_namespace: 'http://russianpost.org/sms-info/data'
    properties:
        __value:
            expose: true
            xml_value: true
            access_type: public_method
            accessor:
                getter: value
                setter: value
            type: string
