a3mg\RussianPostBundle\Model\OperationHistoryRequest:
    xml_root_name: OperationHistoryRequest
    xml_root_namespace: 'http://russianpost.org/operationhistory/data'
    properties:
        barcode:
            expose: true
            access_type: public_method
            serialized_name: Barcode
            xml_element:
                namespace: 'http://russianpost.org/operationhistory/data'
            accessor:
                getter: getBarcode
                setter: setBarcode
            type: string
        messageType:
            expose: true
            access_type: public_method
            serialized_name: MessageType
            xml_element:
                namespace: 'http://russianpost.org/operationhistory/data'
            accessor:
                getter: getMessageType
                setter: setMessageType
            type: integer
