a3mg\RussianPostBundle\Model\SmsHistoryRequest:
    xml_root_name: SmsHistoryRequest
    xml_root_namespace: 'http://russianpost.org/sms-info/data'
    properties:
        barcode:
            expose: true
            access_type: public_method
            serialized_name: Barcode
            xml_element:
                namespace: 'http://russianpost.org/sms-info/data'
            accessor:
                getter: getBarcode
                setter: setBarcode
            type: string
        language:
            expose: true
            access_type: public_method
            serialized_name: Language
            xml_element:
                namespace: 'http://russianpost.org/sms-info/data'
            accessor:
                getter: getLanguage
                setter: setLanguage
            type: string
