a3mg\RussianPostBundle\Model\OperationHistoryData:
    xml_root_name: OperationHistoryData
    xml_root_namespace: 'http://russianpost.org/operationhistory/data'
    properties:
        historyRecord:
            expose: true
            access_type: public_method
            serialized_name: historyRecord
            xml_element:
                namespace: 'http://russianpost.org/operationhistory/data'
            accessor:
                getter: getHistoryRecord
                setter: setHistoryRecord
            xml_list:
                inline: true
                entry_name: historyRecord
                namespace: 'http://russianpost.org/operationhistory/data'
            type: array<a3mg\RussianPostBundle\Model\OperationHistoryRecordType>
