a3mg\RussianPostBundle\Model\FinanceParametersType:
    properties:
        payment:
            expose: true
            access_type: public_method
            serialized_name: Payment
            xml_element:
                namespace: 'http://russianpost.org/operationhistory/data'
            accessor:
                getter: getPayment
                setter: setPayment
            type: integer
        value:
            expose: true
            access_type: public_method
            serialized_name: Value
            xml_element:
                namespace: 'http://russianpost.org/operationhistory/data'
            accessor:
                getter: getValue
                setter: setValue
            type: integer
        massRate:
            expose: true
            access_type: public_method
            serialized_name: MassRate
            xml_element:
                namespace: 'http://russianpost.org/operationhistory/data'
            accessor:
                getter: getMassRate
                setter: setMassRate
            type: integer
        insrRate:
            expose: true
            access_type: public_method
            serialized_name: InsrRate
            xml_element:
                namespace: 'http://russianpost.org/operationhistory/data'
            accessor:
                getter: getInsrRate
                setter: setInsrRate
            type: integer
        airRate:
            expose: true
            access_type: public_method
            serialized_name: AirRate
            xml_element:
                namespace: 'http://russianpost.org/operationhistory/data'
            accessor:
                getter: getAirRate
                setter: setAirRate
            type: integer
        rate:
            expose: true
            access_type: public_method
            serialized_name: Rate
            xml_element:
                namespace: 'http://russianpost.org/operationhistory/data'
            accessor:
                getter: getRate
                setter: setRate
            type: integer
