a3mg\RussianPostBundle\Model\DataExchangeESPP\Password:
    xml_root_name: Password
    xml_root_namespace: 'http://www.russianpost.org/RTM/DataExchangeESPP/Data'
    properties:
        __value:
            expose: true
            xml_value: true
            access_type: public_method
            accessor:
                getter: value
                setter: value
            type: string
