a3mg\RussianPostBundle\Model\DataExchangeESPP\PostalOrderEventsForMailFault:
    xml_root_name: PostalOrderEventsForMailFault
    xml_root_namespace: 'http://www.russianpost.org/RTM/DataExchangeESPP/Data'
